# Generated by Django 5.2.7 on 2025-10-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_gradescale_student_department_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescale',
            name='grade_points',
            field=models.IntegerField(),
        ),
    ]
