# Generated by Django 5.2.7 on 2025-10-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('units', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmental_courses', to='departments.departments')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_courses', to='faculty.faculties')),
            ],
        ),
    ]
